# Generated by Django 4.2 on 2023-04-11 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_recipes_userprofile_delete_user_recipes_recipes_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipes',
            new_name='Recipe',
        ),
    ]
