# Generated by Django 4.2 on 2023-04-11 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0003_rename_recipes_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
