# Generated by Django 4.2 on 2023-04-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0004_remove_userprofile_name_remove_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
