# Generated by Django 4.2 on 2023-04-11 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0005_userprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipes_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='app_api.userprofile'),
        ),
    ]
