# Generated by Django 4.2 on 2023-04-11 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0007_rename_recipes_id_recipe_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='user_profile',
        ),
    ]
