# Generated by Django 4.2 on 2023-04-12 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0008_remove_recipe_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='equipment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='app_api.userprofile'),
        ),
    ]
