# Generated by Django 4.2 on 2023-04-14 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0012_alter_recipe_image_alter_userprofile_image'),
        ('app_api', '0013_recipe_imageurl_alter_recipe_image_and_more'),
    ]

    operations = [
    ]
