# Generated by Django 4.2 on 2023-04-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0015_alter_userprofile_options_alter_userprofile_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='default_username', max_length=150, unique=True),
        ),
    ]
